name: ESLint Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint Checks
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --fix-all --max-warnings 0
          if [ $? -ne 0 ]; then
          echo "ESLint errors found. Please fix before merging."
          exit 1
          fi
